name: firebase_auth_oauth_example
description: Demonstrates how to use the firebase_auth_oauth plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_auth_oauth:
    path: "../"

flutter:
  uses-material-design: true
