name: firebase_auth_oauth_web
description: Web implementation for `firebase_auth_oauth`
version: 0.1.0+6
author: Amr Yousef <contact@amryousef.me>
homepage: https://github.com/amrfarid140/firebase_auth_oauth/tree/master/firebase_auth_oauth_web

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_auth_oauth_platform_interface: ^0.1.0+3
  firebase: ^7.0.0
  js: ^0.6.1
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthOAuthWeb
        fileName: firebase_auth_oauth_web.dart
