name: firebase_auth_oauth
description: A Flutter plugin that makes it easy to perform OAuth sign in flows using FirebaseAuth. It also includes support for Sign in by Apple for Firebase.
version: 0.2.4
homepage: https://github.com/amrfarid140/firebase_auth_oauth/tree/master/firebase_auth_oauth
publish_to: none
environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_auth_oauth_platform_interface:
    path: "../firebase_auth_oauth_platform_interface"
  firebase_auth_oauth_web:
    path: "../firebase_auth_oauth_web"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.amryousef.apple.auth.firebase_auth_oauth
        pluginClass: FirebaseAuthOAuthPlugin
      ios:
        pluginClass: FirebaseAuthOAuthPlugin
      web:
        default_package: firebase_apple_auth_web
